### ISSUE TITLE
Windows exe ?

### ISSUE THREAD

**Issue by chrizilla** [Lazza/RecuperaBit#105]
Congratulations on your excellent program.
Is there a executable file for Windows somewhere for users who don't have Python ?

**Comment by Lazza** [comment]
Currently there is no plan to release packaged executables. You should be able to build one with Pyinstaller, though.

**Comment by chrizilla** [comment]
thank you for the valuable Pyinstaller tip!

**Comment by chrizilla** [comment]
lol, ok I couldn't find any executable file for Pyinstaller either 😄 
There aren't any here: https://pypi.org/project/pyinstaller/#files
What do I have to do? thanks.

**Comment by chrizilla** [comment]
@Lazza can you help me? thanks

**Comment by NicolasCARPi** [comment]
@chrizilla If you don't have the knowledge to build an executable yourself, why don't you install python? It's very easy to install on windows: *it is in the windows store* and this project being a python project I don't see why there would be a need for an executable. It's also not the kind of project that you need to install on multiple machines.

Furthermore, building an executable from python is not always an easy task and most of the time it's a waste of time for the dev.

**Comment by chrizilla** [comment]
@NicolasCARPi thanks. As this is a rescue software, it should not be installed on the target machine. The best use is to have a portable version on a USB stick. That's why a .exe file would come in handy, because I could simply run it from a USB stick on any machine.

**Comment by Lazza** [comment]
The documentation for Pyinstaller is here: https://pyinstaller.readthedocs.io/

If your analysis machine is Windows-based, you can install Python on it. If you are planning to run RecuperaBit on the same system where the damaged file system is, why don't you opt to use one of the usual digital forensics distros out there?

Both CAINE and Tsurugi feature a pretty recent version of RecuperaBit.
