### ISSUE TITLE
Getting a memory error at the end of the process

### ISSUE THREAD

**Issue by Leandrocvida** [Lazza/RecuperaBit#11]
Hi I had a similar problem then what is listed here: http://stackoverflow.com/questions/37539950/corrupt-ntfs-folder-not-accessible-from-either-windows-mas-osx-or-linux
The hard drive that had the problem is an ssd, and it had my windows install on it. I can see all folders when i mount the drive with the exception of 2, the "c:\Users" being one of them. I created a partition and installed linux on another HD. 
Since the drive doesn't seem to be damaged i ran the application directly on it. The first time it ran it crashed midway, i don't know what happened the terminal just froze, and no savefile was created. I ran the application 4 times since then, the first one took a long time (around 20 hours) and created a savefile. The other other ones ran much faster around 2 hours. But they all end up the same with the message:

```
INFO:root:Found NTFS boot sector at sector 234229752
INFO:root:First scan completed
INFO:root:Parsing MFT entries
INFO:root:Parsing INDX records
INFO:root:Reading boot sectors
DEBUG:root:Dropping bogus NTFS partition with MFT position 27585690 generated by MFT mirror of partition at offset 27580528
DEBUG:root:Dropping bogus NTFS partition with MFT position 65746898 generated by MFT mirror of partition at offset 65741736
DEBUG:root:Dropping bogus NTFS partition with MFT position 112 generated by MFT mirror of partition at offset 0
INFO:root:Finding partition geometry
INFO:root:Finalizing MFT reconstruction of partition at offset 27580528
INFO:root:Adding extra attributes from $ATTRIBUTE_LIST
INFO:root:Adding ghost entries from $INDEX_ALLOCATION
INFO:root:Finalizing MFT reconstruction of partition at offset 65741736
INFO:root:Adding extra attributes from $ATTRIBUTE_LIST
INFO:root:Adding ghost entries from $INDEX_ALLOCATION
INFO:root:Finalizing MFT reconstruction of partition at offset 0
INFO:root:Adding extra attributes from $ATTRIBUTE_LIST

But then a series of messages appear saying:
WARNING:root:Cannot read sector(s). Filling with 0x00. Offset: 119785142 Size: 2 Bsize: 512

After a bunch of these, the folowing apppears:

Traceback (most recent call last):
  File "main.py", line 328, in <module>
    main()
  File "main.py", line 310, in main
    parts.update(scanner.get_partitions())
  File "/home/leandro/RecuperaBit-master/recuperabit/fs/ntfs.py", line 841, in get_partitions
    self.finalize_reconstruction(part)
  File "/home/leandro/RecuperaBit-master/recuperabit/fs/ntfs.py", line 674, in finalize_reconstruction
    self.add_from_attribute_list(parsed, part, node.offset)
  File "/home/leandro/RecuperaBit-master/recuperabit/fs/ntfs.py", line 629, in add_from_attribute_list
    _integrate_attribute_list(parsed, part, image)
  File "/home/leandro/RecuperaBit-master/recuperabit/fs/ntfs.py", line 221, in _integrate_attribute_list
    entries += attribute_list_parser(dump)
  File "/home/leandro/RecuperaBit-master/recuperabit/fs/ntfs_fmt.py", line 118, in attribute_list_parser
    content.append(decoded)
MemoryError
```

Now I'm lost on what to do, and what could be causing the problem. And when I try to run the "recoverable" command it just says "command not found", I'm assuming because the program crashed...

**Comment by Lazza** [comment]
The `MemoryError` seems to indicate you don't have enough memory to hold the reconstructed list of attributes (that seems a bit odd but could happen). How much RAM do you have?

**Comment by Leandrocvida** [comment]
I have 12 gb of ram, the Ssd has 110 gb.

**Comment by Leandrocvida** [comment]
ran memtest to check the ram memories and they have no errors either...

**Comment by Lazza** [comment]
To be precise, a `MemoryError` does not mean that your memory is damaged. It just indicates that there are a lot of entries that get stored in memory up to the point where the program crashes. This is a bit weird given that we are only considering the index records.

Anyways, you could try commenting out this line:
https://github.com/Lazza/RecuperaBit/blob/ba4ebf6cbe18dfc3ba9e95cffd75527e2d47bc9c/recuperabit/fs/ntfs.py#L841

Then run the program again. The output will be a bit less precise because it won't include information from the index records, but you could still use the `locate` command to search for `Users` or any name you want.

**Comment by Leandrocvida** [comment]
It worked like a charm! I would like to use this space to thank you for your help, and for developing and providing this application for free. It really saved my bacon! I had tried everything you can think of for 2 weeks on this hd. And thanks to you, finally, I recovered all my data. This tool that you developed is amazing! Once again thank you soo much for the help!

**Comment by Lazza** [comment]
Great! Although it would be interesting to have a way to reproduce that problem with memory consumption on attribute lists. Unfortunately, without having a problematic disk image myself I cannot really do anything about that. 😞
