### ISSUE TITLE
Lot of files with zero length

### ISSUE THREAD

**Issue by emmrichd** [Lazza/RecuperaBit#128]
Hello,

I get a lot of files with zero length, even though they should contain something:
`              StGrArch_elster_23.09.2024_17.16.pfx:Zone.Identifier (Id: 166056:Zone.Identifier, Offset: 1448388096, Offset bytes: 741574705152, Size: 50.00 B) 
              StGrArch_elster_23.09.2024_17.16.pfx (Id: 166056, Offset: 1448388096, Offset bytes: 741574705152, Size: 12.87 KB) 
              Steuer 2023/ (Id: 171901, Offset: 1448399786, Offset bytes: 741580690432) 
`
This is an example of a file which, when recovered, has not contents.
I run it with pypy3 under Windows 11.
Regards, Tomte

**Comment by emmrichd** [comment]
Can the reason be, that I ran out of RAM? I saw no complaints, however?

**Comment by Lazza** [comment]
That's an ADS for the information of the downloaded files.

https://stackoverflow.com/a/4496754/1101509

Nevertheless, how big is the disk image? Did it use NTFS compression on some files?

**Comment by Lazza** [comment]
> I cannot tell, if NTFS compression was used

It should warn you about this in the logs, during recovery. Maybe you can try to restore only one directory so that you get fewer log messages.

> Reading the link you provided, I see no solution at hand

The link is not a solution, it is a description about what an ADS is.
