### ISSUE TITLE
KeyError: 'content'

### ISSUE THREAD

**Issue by labenech** [Lazza/RecuperaBit#15]
Hi,

while running : python2.7 main.py image -o recov -s log.save
i got the following error :

````
INFO:root:Parsing MFT entries
Traceback (most recent call last):
  File "main.py", line 328, in <module> main()
  File "main.py", line 310, in main  parts.update(scanner.get_partitions())
  File "/mnt/hdd/RecuperaBit-master/recuperabit/fs/ntfs.py", line 719, in get_partitions  part.add_file(NTFSFile(parsed, position, ads=ads_name))
  File "/mnt/hdd/RecuperaBit-master/recuperabit/fs/ntfs.py", line 303, in __init__    parent_id = filenames[0]['content']['parent_entry']
KeyError: 'content'
````
any idea ?
Thanks

**Comment by Lazza** [comment]
Pretty strange. Could you update line 303 in file `ntfs.py` to read like this?

    try: parent_id = filenames[0]['content']['parent_entry']; except: print filenames; exit(1)

Then please run it again so it prints the contents of `filenames`.

Thank you.

**Comment by labenech** [comment]
Hello Andrea

I'm in vacation for few days ... I'll try this when I'll be back home :-)

Thanks
Laurent





<div>-------- Message d'origine --------</div><div>De : Andrea Lazzarotto <notifications@github.com> </div><div>Date :01/08/2017  16:03  (GMT+01:00) </div><div>A : Lazza/RecuperaBit <RecuperaBit@noreply.github.com> </div><div>Cc : labenech <lbenichou@free.fr>,Author <author@noreply.github.com> </div><div>Objet : Re: [Lazza/RecuperaBit] KeyError: 'content' (#15) </div><div>
</div>Pretty strange. Could you update line 303 in file ntfs.py to read like this?

try: parent_id = filenames[0]['content']['parent_entry']; except: print filenames; exit(1)
Then please run it again so it prints the contents of filenames.

Thank you.

**Comment by Lazza** [comment]
@labenech could you provide some feedback on the topic?

**Comment by labenech** [comment]
hello Andrea,

I'm back from holidays, I was in nice trip in Sicilia :-) 

I'll give you feedback this week ...

thanks

**Comment by labenech** [comment]
@Lazza here is the answer : 

`[{'name_length': 209, 'name': '', 'allocated_size': 131409966874739696, 'non_resident': 108, 'name_off': 33175, 'runlist': [], 'initialized_size': 131440727380114724, 'start_VCN': 18446709441267486943L, 'runlist_offset': 48420, 'length': 120, 'dump_offset': 152, 'flags': 57472, 'end_VCN': 6192449487634794, 'real_size': 131440720423980326, 'compression_unit': 10370, 'type': 48, 'id': 65535}, {'content_off': 24, 'name_length': 0, 'name': '', 'non_resident': 0, 'content_size': 294, 'name_off': 0, 'content': {'name_length': 114, 'name': u'amd64_microsoft-windows-i..timezones.resources_31bf3856ad364e35_10.0.14393.1358_sr-..-rs_869f7fcd9831bc0d.manifest', 'allocated_size': 4096, 'access_time': datetime.datetime(2017, 7, 9, 11, 18, 58, 11473), 'MFT_modification_time': datetime.datetime(2017, 7, 9, 11, 7, 22, 398031), 'creation_time': datetime.datetime(2017, 7, 9, 11, 18, 58, 11473), 'modification_time': datetime.datetime(2017, 6, 3, 20, 51, 27, 473970), 'flags': 32, 'parent_entry': 362, 'parent_seq': 22, 'namespace': 1, 'real_size': 2541}, 'length': 320, 'dump_offset': 272, 'flags': 0, 'type': 48, 'id': 5}]`
