### ISSUE TITLE
Add command to manually merge partitions

### ISSUE THREAD

**Issue by reasv** [Lazza/RecuperaBit#19]
It would be useful, as highlighted by issue #18 , to implement a command to manually merge partitions that are recognized as separate by RecuperaBit, but which are known to be part of the same original partition.

**Comment by Lazza** [comment]
I have added a basic merge functionality. Please note that the only check that is performed is that both partitions exist and are of the same type.

There is no check for conflicting files or on the boundaries of the partitions. You should probably merge the small partitions as the second parameter, while the large partition should be the first parameter.
