### ISSUE TITLE
Error: No such file or directory

### ISSUE THREAD

**Issue by urgrueA** [Lazza/RecuperaBit#2]
Thanks for your previous len() fix, it worked. This software is outstanding when it comes to borked indexes, and I have recovered most of my filesystem. I am running Windows 7 x64 with pypy 32bit btw, and file recovery is quite fast. However, there is another problem. I used the command

    recover 7 5

for partition #7, and here is the where the output gets interesting:

```
...
...
INFO:root:Restoring #122688 Root\backup\Quiz\websites\walkthroughs\www.thecomputershow.com\computershow\previews\SOURCE  Activision, Inc. -0-
 10\18\96_\CONTACT_  Andrea Kaimowitz or Cindy Miller, or Press_  Miriam Adler or Erika Brown, of Morgen-Walke Associates, 212-850-5600.html
Traceback (most recent call last):
  File "main.py", line 309, in <module>
    main()
  File "main.py", line 306, in main
    interpret(cmd, arguments, parts, shorthands, args.outputdir)
  File "main.py", line 185, in interpret
    logic.recursive_restore(myfile, part, partition_dir)
  File "D:\Program Files (x86)\RecuperaBit\recuperabit\logic.py", line 255, in recursive_restore
    recursive_restore(child, part, outputdir, make_dirs=False)
  File "D:\Program Files (x86)\RecuperaBit\recuperabit\logic.py", line 255, in recursive_restore
    recursive_restore(child, part, outputdir, make_dirs=False)
  File "D:\Program Files (x86)\RecuperaBit\recuperabit\logic.py", line 255, in recursive_restore
    recursive_restore(child, part, outputdir, make_dirs=False)
  File "D:\Program Files (x86)\RecuperaBit\recuperabit\logic.py", line 255, in recursive_restore
    recursive_restore(child, part, outputdir, make_dirs=False)
  File "D:\Program Files (x86)\RecuperaBit\recuperabit\logic.py", line 255, in recursive_restore
    recursive_restore(child, part, outputdir, make_dirs=False)
  File "D:\Program Files (x86)\RecuperaBit\recuperabit\logic.py", line 255, in recursive_restore
    recursive_restore(child, part, outputdir, make_dirs=False)
  File "D:\Program Files (x86)\RecuperaBit\recuperabit\logic.py", line 255, in recursive_restore
    recursive_restore(child, part, outputdir, make_dirs=False)
  File "D:\Program Files (x86)\RecuperaBit\recuperabit\logic.py", line 255, in recursive_restore
    recursive_restore(child, part, outputdir, make_dirs=False)
  File "D:\Program Files (x86)\RecuperaBit\recuperabit\logic.py", line 241, in recursive_restore
    with codecs.open(restore_path, 'wb') as outfile:
  File "D:\Program Files (x86)\RecuperaBit\lib-python\2.7\codecs.py", line 884, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: u'j:\\Partition7\\Root\\backup\\Quiz\\websites\\walkthroughs\\www.thecomputershow.com\\computershow\\previews\\SOURCE  Activision, Inc. -0-     10\\18\\96_\\CONTACT_  Andrea Kaimowitz or Cindy Miller, or Press_  Miriam Adler or Erika Brown, of Morgen-Walke Associates, 212-850-5600.html' 

>
```

After this, I have to restart and enter file and directory references by hand using the csv file. The next commands would be

    recover 7 122689
    recover 7 122690
    ...

until I hit a directory, which moves faster, then repeat as necessary. As you can appreciate, this is quite laborious. This has happened several times with different files. Maybe the output path is too long? 

Anyway, is it possible to have RecuperaBit flag this kind of error and skip the file, rather than force me to traverse the tree by hand?

Thanks

urgrueA

**Comment by Lazza** [comment]
> Maybe the output path is too long?

Yes, this is correct. It's a limitation [imposed by Windows](http://stackoverflow.com/q/265769/1101509) of roughly 260 characters. The path:

    \backup\Quiz\websites\walkthroughs\www.thecomputershow.com\computershow\previews\SOURCE  Activision, Inc. -0- 10\18\96_\CONTACT_  Andrea Kaimowitz or Cindy Miller, or Press_  Miriam Adler or Erika Brown, of Morgen-Walke Associates, 212-850-5600.html

Has 247 characters, which must be added to the path of your `recuperabit_output` (or similar) directory. Please note that this is specific to Windows. On Linux, the limit is [4096 characters for paths](http://serverfault.com/a/306726/200410).

So those files can be recovered if you run RecuperaBit on Linux. In any case, a check with an explicit error message definitely does not hurt.

**Comment by Kaos-Industries** [comment]
Is there currently support in the program for a way around this? Because from past experience with other utilities, I know my target drive has at least one of those files, and I wouldn't want to waste days running the program only to be stopped dead in my tracks (again) by this error.

**Comment by Lazza** [comment]
This has already been closed one year ago. Nevertheless the correct solution is not to use Windows.
