### ISSUE TITLE
be slightly more verbose

### ISSUE THREAD

**Issue by jampy** [Lazza/RecuperaBit#22]
Just a suggestion for a minor improvement: :-)

I'm using RecuperaBit for the first time and right after starting the program I got this prompt:

```
Type [Enter] to start the analysis or "exit" / "quit" / "q" to quit:
```

After pressing [Enter] nothing happens on the screen. A little `Scanning the image, this might take quite some time...` or anything similar (or even a progress bar) would be nice.

In my case I wondered if RecuperaBit was still waiting for input, had locked up or whatever. After a few minutes I had to check the disk I/O statistics to understand that RecuperaBit was actually reading heavily from the disk (since I use RecuperaBit remotely I can't hear the disks working, so I have absolutely no feedback...).

That said, your program looks very promising. Keep up the good work!

**Comment by Lazza** [comment]
Yes, I totally agree. Currently the program logs only when something interesting is found. This is not ideal. I think the best solution would be to use a progress bar and to move logging to a file only, or to scroll only some lines.

I have to think how to best implement it. Also, while the general data model and the reconstruction algorithms are well written, the text interface in the main program is a bit of a mess. That part needs some refactoring which will surely include your suggestion.

**Comment by jampy** [comment]
Agreed. For the start, a little "I'm doing something" info would be a simple and useful start.. ;-)
