### ISSUE TITLE
Can't use "real drive" as input

### ISSUE THREAD

**Issue by Kaos-Industries** [Lazza/RecuperaBit#23]
Hey there, I came across the program via your recommendation on SE. As I mentioned on there, I've been trying to recover the directory structure from a 2TB drive for months and have used a ton of programs in the process, including GetDataBack and TestDisk, so will be very impressed if RecuperaBit lives up to the level of capability that your Masters thesis outlines it can.

Unfortunately, I can't seem to get it to work with my drive using Cygwin on Windows 7, even though the RB's documentation states it should work with "real drives". I'm not an expert in `bash` and/or Python by any means, so it's possible I'm getting the syntax wrong.

![hello](https://user-images.githubusercontent.com/16962031/30769804-58c5ddf8-a018-11e7-95c9-4d86442d8a03.jpg)

Thanks in advance for your help, I really appreciate it.

**Comment by Lazza** [comment]
Yes it does, but you need proper permissions (usually the root account). Also, why are you using Windows?

**Comment by Kaos-Industries** [comment]
Because Windows is my primary OS, as it is for ~90% of the world. I also have Administrator permissions on it, so I can't see any reason RecuperaBit shouldn't have worked on it. 

Regardless, because of the MAX_FILE_PATH issue, I'm forced to run from an Ubuntu LiveUSB and run RecuperaBit from there. However, I'm still getting the same error, even when running as sudo:

![screenshot from 2017-09-23 21-29-15](https://user-images.githubusercontent.com/16962031/30777335-2b29558a-a0b0-11e7-8350-bf5026645ecc.png)

**Comment by Lazza** [comment]
The device file should NOT have a trailing slash. Also, the save file should be a file name, not a directory. Please try again.

RecuperaBit might work on Windows however it is neither tested nor endorsed.

**Comment by Kaos-Industries** [comment]
I see, the trailing `/`seems to have been be the problem. Regarding the save file, I was under the impression the `-s` switch was the directory in which the save file would be placed and the program would handle the generation of the actual file. Should the filename be a particular extension or will a .txt file be sufficient?

**Comment by Lazza** [comment]
You can use any file name you like. The extension is not important. I am going to close this now since you are able to run it on a real drive on Linux (in case anyone was wondering, it works on macOS as well).
