### ISSUE TITLE
Error parsing MFT entries

### ISSUE THREAD

**Issue by ascattolini** [Lazza/RecuperaBit#24]
Hi,
I am trying to recover an NTFS formatted disk (for your information there is an underlying RAID 5 (3 disks + 1 spare)) whose partition informations are lost (even MFT and MFT mirror are lost!). I have tried the most updated RecuperaBit (1.1.1), launching the command:

    recuperabit -s /mnt/tera8/atpmicrobusrecovery/savefile -o /mnt/tera8/atpmicrobusrecovery /dev/cciss/c0d0

and obtaining:

```
[.....omissis.....]
INFO:root:First scan completed
INFO:root:Parsing MFT entries
Traceback (most recent call last):
  File "/usr/local/bin/recuperabit", line 358, in <module>
    main()
  File "/usr/local/bin/recuperabit", line 340, in main
    parts.update(scanner.get_partitions())
  File "/mnt/tera8/rb/RecuperaBit/recuperabit/fs/ntfs.py", line 722, in get_partitions
    part.add_file(NTFSFile(parsed, position, ads=ads_name))
  File "/mnt/tera8/rb/RecuperaBit/recuperabit/fs/ntfs.py", line 270, in __init__
    ads_suffix = ':' + ads if ads != '' else ads
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

Any idea?
Thanks.

**Comment by runningnak3d** [comment]
I am getting the same error:

```
INFO:root:First scan completed
INFO:root:Parsing MFT entries
Traceback (most recent call last):
  File "main.py", line 358, in <module>
    main()
  File "main.py", line 340, in main
    parts.update(scanner.get_partitions())
  File "/home/swango/dev/RecuperaBit/recuperabit/fs/ntfs.py", line 722, in get_partitions
    part.add_file(NTFSFile(parsed, position, ads=ads_name))
  File "/home/swango/dev/RecuperaBit/recuperabit/fs/ntfs.py", line 270, in __init__
    ads_suffix = ':' + ads if ads != '' else ads
TypeError: unsupported operand type(s) for +: 'str' and 'NoneType'
```
I am trying to recover a 4TB drive that I accidentally overwrote the first 580 megs (messed up a dd statement trying to write an iso image to a USB stick).

If you have any ideas, it would be GREATLY appreciated. I can provide any further details that you might need.

**Comment by Lazza** [comment]
It should be fully fixed now. Please try with the latest snapshot and report if it worked. 😁

**Comment by ascattolini** [comment]
Last result:

INFO:root:First scan completed
INFO:root:Parsing MFT entries
ERROR:root:Cannot handle multiple attribute $STANDARD_INFORMATION
ERROR:root:Problem parsing record on sector 2895556
ERROR:root:Cannot handle multiple attribute $STANDARD_INFORMATION
ERROR:root:Problem parsing record on sector 2895698
ERROR:root:Cannot handle multiple attribute $STANDARD_INFORMATION
ERROR:root:Problem parsing record on sector 1465432
ERROR:root:Cannot handle multiple attribute $STANDARD_INFORMATION
ERROR:root:Problem parsing record on sector 72507203
ERROR:root:Cannot handle multiple attribute $STANDARD_INFORMATION
ERROR:root:Problem parsing record on sector 72507285
ERROR:root:Cannot handle multiple attribute $STANDARD_INFORMATION
ERROR:root:Problem parsing record on sector 2808500
Killed

Should I open a different issue?

**Comment by Lazza** [comment]
Entries with more than one `$STANDARD_INFORMATION` are not valid so they are skipped. Why did you kill the program?

**Comment by runningnak3d** [comment]
I am sure he didn't kill it, the OOM process killer did, as it did for me:

```
[14962149.329239] Out of memory: Kill process 27910 (pypy) score 392 or sacrifice child
[14962149.329284] Killed process 27910 (pypy) total-vm:13495036kB, anon-rss:13321072kB, file-rss:7808kB, shmem-rss:0kB
[14962150.705010] oom_reaper: reaped process 27910 (pypy), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

Is it possible to do the sort on disk (a file?) instead of in memory? I have 16gigs, and except for a very small base OS, all 16gigs, and another 32gigs of swap, are free.

**Comment by ascattolini** [comment]
I did not killed the program... It was suicide....

**Comment by Lazza** [comment]
Ah, sorry. 😅 

It could simply be that there are a huge amount of entries. Could you check #6 and #11 to see if any workaround works? Also, it would be a good idea to discuss this issue separately from this bug.

I can't tell if we can really do a lot about big RAM usage, but we could try something.

**Comment by ascattolini** [comment]
Neither workaround works... Both lead to the same result (however I did not tried them together). For issue #6 I only added what you suggested within the comment dated 30 Nov 2016 (avoiding previous debugging comments).
For issue #11 I simply commented out what you indicated.
Is there any debugging I can enable to help?

**Comment by runningnak3d** [comment]
I opened a new issue dealing specifically with the memory issue: https://github.com/Lazza/RecuperaBit/issues/25

**Comment by Lazza** [comment]
@ascattolini please add yourself to the followers of #25. Thank you.
