### ISSUE TITLE
Savefile not flushed after final write

### ISSUE THREAD

**Issue by evildeeds** [Lazza/RecuperaBit#27]
I ran into a OOM-kill after which the savefile was broken (unexpected eof), kind of breaks the purpose for having a save-file.

I suggest closing (or flushing) the savefile before continuing to avoid this issue. Diff included.

```diff --git a/main.py b/main.py
index 5cea733..e6ed491 100755
--- a/main.py
+++ b/main.py
@@ -333,6 +333,7 @@ def main():
         logging.info('Saving results to %s', args.savefile)
         savefile = open(args.savefile, 'wb')
         pickle.dump(interesting, savefile)
+        savefile.close()
 
     # Ask for partitions
     parts = {}```

**Comment by Lazza** [comment]
Good idea, thank you. Although, to be fair the main file needs a bit of a revamp in general terms.

Also, the need for large amount of memory is a separate topic where unfortunately the savefile won't help much.
