### ISSUE TITLE
Denial of service

### ISSUE THREAD

**Issue by evildeeds** [Lazza/RecuperaBit#28]
Since memory issues appeared common I decided to do a quick code inspection and I did spot an actual problem, honestly since I'm not familiar with NTFS data-structures I can't tell for sure if there are other problems, for example reading too few sectors when dumping attribute lists.

Anyway the problem will cause RecuperaBit to go into an infinite loop while allocating an attribute list eventually in my case causing an OOM-kill.

A list a is equal to a[None:] thus ensuring that the loop never terminates and that the same faulty structure is reparsed (where length == None due to being out-of-bounds) and added to the content list each iteration. Quick fix included below.

```diff --git a/recuperabit/fs/ntfs_fmt.py b/recuperabit/fs/ntfs_fmt.py
index c7b3dd9..160aa8a 100644
--- a/recuperabit/fs/ntfs_fmt.py
+++ b/recuperabit/fs/ntfs_fmt.py
@@ -113,7 +113,7 @@ def attribute_list_parser(dump):
             ('id', ('i', 24, 24))
         ])
         length = decoded['length']
-        if length == 0:
+        if length == None or length == 0:
             break
         content.append(decoded)
         dump = dump[length:]
```

**Comment by Lazza** [comment]
**Amazing find,** thank you. Actually I think we could just use `if not length`.

Would you like to make a PR and take the credit or can I simply patch it myself?

**Comment by evildeeds** [comment]
If you wish to credit me anything simply list me as a contributor.

```
>>> not None
True
>>> not 0
True
```
Yeah, "not length" will work as well since I'm sure that the number cannot be zero given how your numeric parser works. But thinking about it I would still prefer to read "length == None or length <= 0" since it is then immediately obvious that there is no problem without having to inspect your parser.

But that reminds me, the built-in unpack function uses "i" as signed and "I" (uppercase "i") as unsigned but you used "+i" to indicate a signed integer, somewhat confusing if you ask me.

**Comment by evildeeds** [comment]
As a side note what I used RecuperaBit for: I have a dd_rescue dump from a failing mechanical hard drive (320GB), and its missing about 1,5MB worth of raw data, I did manage to recover the files I was interested in but some data in it is still missing. Anyway this is much better then any other tool since the file is encrypted, so no file carving could save it from a non-repariable and non-mountable filesystem.

As such I'm quite pleased with the results. Also if you happen to have vmware disk-images you will get thousands of partial filsystems.

**Comment by Lazza** [comment]
> somewhat confusing if you ask me

At the time I needed a way to quickly remember which "i" was signed, so I added a plus sign for this reason. 😅 

> Anyway this is much better then any other tool since one file is encrypted

Thank you!

> RecuperaBit required about 10GB worth of ram

Woah that's still quite a lot. 🤔
