### ISSUE TITLE
Add a feature: given a file it prints all the parents

### ISSUE THREAD

**Issue by atti84it** [Lazza/RecuperaBit#29]
I needed to recover one directory (call it "my documents"). I performed a scan, I created a list.csv file, but it was very difficult to locate the entry due to the fact that my 1 GB RAM netbook hardly managed to open a 30 mb csv file with libreoffice. I couldn't use CTRL + F function because it freezed libreoffice. I scrolled down the records until I found one file that I knew it was nested in my documents. I took note of the parent ID, then using "grep" I recursively found the ID of the folder I was looking for. It would be cool to avoid this manual recursive use of grep command, it would be nice to specify an entry and recursively get all the parents until root folder.
**Note** that I couldn't directly grep "my documents" string due to the fact that the corresponding entry in csv file was:
`290396,-1,"Dir_290396",None,None,None,0,0.00 B,None,None,1,,1`
Andrea, says it's because MFT entry of the file was missing.

**Comment by Lazza** [comment]
Until I find the time to rewrite a better text interface, I have added a `traceback` command:

```
> traceback 0 66
[66] Root/.Trash-1000/expunged/2874436234
[72] Root/.Trash-1000/expunged
[67] Root/.Trash-1000
[5] Root
```

**Comment by atti84it** [comment]
:O ! complimenti!
