### ISSUE TITLE
No len()

### ISSUE THREAD

**Issue by runningnak3d** [Lazza/RecuperaBit#31]
The following is from rev: https://github.com/Lazza/RecuperaBit/commit/f03f5e98b71f0ce93e483b5e6afb94b1546dba46

I am using Python 2.7. Do I need an older version?

INFO:root:Found NTFS boot sector at sector 7813967871
INFO:root:First scan completed                                                                                                        
INFO:root:Parsing MFT entries                                                                                                         
INFO:root:Parsing INDX records                                                                                                        
INFO:root:Reading boot sectors                                                                                                        
3230662656 -> 
Traceback (most recent call last):
  File "./main.py", line 385, in <module>
    main()
  File "./main.py", line 367, in main
    parts.update(scanner.get_partitions())
  File "/home/swango/dev/RecuperaBit/recuperabit/fs/ntfs.py", line 782, in get_partitions
    print address, '->', len(partitioned_files[address])
TypeError: object of type 'NTFSPartition' has no len()

**Comment by Lazza** [comment]
Python 2.7 is fine but the error you get does not make sense.

    print address, '->', len(partitioned_files[address])

There is no such code in `ntfs.py`: https://github.com/Lazza/RecuperaBit/blob/f03f5e98b71f0ce93e483b5e6afb94b1546dba46/recuperabit/fs/ntfs.py

**Comment by runningnak3d** [comment]
Sorry about that! That was some debug code that you had me add when trying to figure out the memory issue.

**Comment by Lazza** [comment]
Ah. 😅 Does it work now?

**Comment by runningnak3d** [comment]
It is still parsing INDX records. This is the farthest it has ever gotten. I am guessing it takes as long to parse the index as the MFT?

**Comment by Lazza** [comment]
It actually depends on the complexity of the directory tree of each partition. It definitely takes a while for big drives.

**Comment by runningnak3d** [comment]
@Lazza Just wanted to let you know that it JUST finished. Been running for a little over 13 days - lol. This was on a box with a 3.2Ghz quad core Core i7 and 32gigs of RAM.

Now to see if I can actually save anything.

**Comment by Lazza** [comment]
😮 

With PyPy or cPython? BTW heck, that's a lot. Was it very fragmented?
