### ISSUE TITLE
I don't get it, how do I use this on Windows?

### ISSUE THREAD

**Issue by IndustrialOne** [Lazza/RecuperaBit#37]
Hi, I'm in desperate need to recover an NTFS volume but I can't figure out how to install your Recuperabit python program on Windows and there is no instructions on your website how to do so. I get an error when I try to do python main.py

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Admin>cd c:\python34

c:\Python34>python "M:\RecuperaBit-master\main.py"
  File "M:\RecuperaBit-master\main.py", line 82
    print 'Partition #' + str(i), '->', parts[part]
                      ^
SyntaxError: invalid syntax

c:\Python34>

What gives?

**Comment by Lazza** [comment]
> there is no instructions on your website how to do so

I never said to use it on Windows. 😅 I suggest you use it on a proper UNIX-like OS, but most importantly you should use the right Python version (2.7), not Python 3.

**Comment by IndustrialOne** [comment]
The site says the following: "RecuperaBit can be run on Linux, Windows and macOS provided that Python 2.7 is available on the system."

I didn't realize I had to have the exact version of Python. I'll try it with Python 2.7.

**Comment by Lazza** [comment]
Correct. It can *technically* run on a system with the appropriate Python interpreter. It doesn't mean I *advised to* do it, though. It's a forensic tool, after all. :wink:
