### ISSUE TITLE
Restoring partition content into a different NTFS can break the target file system

### ISSUE THREAD

**Issue by Budovi** [Lazza/RecuperaBit#40]
I've started with an external 1TB HDD (msdos partition table) with a single NTFS partition that was broken by partially overwriting the partition by a smaller FAT partition (< 1.3 GB, possibly not fully written, the partition table was amended though).

The RecuperaBit successfully located the partition and most (if not all) of the files that were lost in the process. As a storage to recover the files I used an additional external 3TB HDD (gpt) with a single NTFS partition, already containing some files. I've made a dedicated directory for the restored files and proceeded with the restore.

For the procedure I've used a GNU/Linux system with `ntfs-3g` implementation of the NTFS support. After the procedure, I've noticed that the destination directory contained NTFS metafiles that appeared as a normal files (`$Mft`, `$Secure`, ...) . Not sure if the permissions of the recovered files were valid either, but the system was able to open them, so I didn't really care, I assume that because of a different color in the terminal listing.

I've decided to delete those metafiles because I thought they are irrelevant for the new filesystem, and after unmounting it I'm no longer able to mount it again. Windows freezes or is stuck in a connect – disconnect loop, GNU/Linux fails with the following output:
```
ntfs_mst_post_read_fixup_warn: magic: 0xff00ffff  size: 4096   usa_ofs: 65535  usa_count: 65535: Invalid argument
Actual VCN (0xffffffffffffffff) of index buffer is different from expected VCN (0x0).
Failed to open $Secure: No such file or directory
```

**So, IMO, RecuperaBit should not try to write metafiles if the target file system is ntfs and/or should use a valid name for them.** The "legit" metafiles should be created by `ntfs-3g` when restored files are written. I'm assuming RecuperaBit uses standard python IO for creating files.

It is also possible that `ntfs-3g` should refuse to write those files in the target file system.

--------
As a side note, any ideas on how to approach fixing the target NTFS now are welcome :slightly_smiling_face: .

**Comment by Lazza** [comment]
> For the procedure I've used a GNU/Linux system with `ntfs-3g` implementation of the NTFS support

This is not advised for a few reasons, the main one being that the `ntfs-3g` driver is **quite slow.** An ext4 partition would be better. For those using RecuperaBit on macOS, APFS is a good choice too.

> I've decided to delete those metafiles because I thought they are irrelevant for the new filesystem

Could you clarify what **exact commands** you typed for this?

> RecuperaBit should not try to write metafiles if the target file system is ntfs and/or should use a valid name for them

**`$` is a valid character in NTFS.** The colon can be used to access ADS's, so ideally if you use it on Windows you get back the files and their original ADS's intact. Reading and writing files should be handled by the file system driver, whether it is implemented by the kernel or by FUSE.

RecuperaBit shall not try to replace or overcome the file system driver. Moreover, the metadata files are only relevant if they are in the root of the drive. RecuperaBit does not support this, it always creates at least two additional levels of directories (`Partition[n]/Root/`) thus there should not be any issue.

----

> any ideas on how to approach fixing the target NTFS

I would make a backup copy of the important files with Testdisk or, ahem... RecuperaBit 😇 into another ext4 drive and then try to fix it with `chkdsk` on Windows.

**Comment by Budovi** [comment]
> This is not advised for a few reasons, the main one being that the ntfs-3g driver is quite slow.

It was the only drive with sufficient disk space available at the time. Not that I would deliberately choose to use NTFS on Linux.

> Could you clarify what exact commands you typed for this?

After checking the output of the `find` command,
```sh
# cd Parition0
# find . -name '$*' -delete
# find . -name '*:*' -delete
# rm -r Root/System\ Volume \Information
```
---------
>> any ideas on how to approach fixing the target NTFS

> I would make a backup copy of the important files with Testdisk or, ahem... RecuperaBit :innocent: 

I've tried RecuperaBit, but it failed miserably. It may have been caused by the fact that the 3TB drive uses 4096B sectors. I've tried to tweak the `sector_size` in `recuperabit/fs/constants.py` without success.

With 512B sector size, it found ~400 partitions typically containing 1024, 2048 files ("coincidence") with a few exceptions, but most of those files were "lost" (i.e. without directory structure information and thus useless) and came from partitions that no longer existed on the drive. I've found the content restored from the original drive, but only as a part of unrecoverable partition.

With 4096B sector size it found ~120k partitions, each containing a single file (maybe 2 of them contained 2). I just gave up.

Luckily, `chkdsk` worked eventually, as the previous problem with it was caused by a bad USB port / stretched cable made a bad contact. So after 2.5 days everything is finally sorted out.

----------
Sadly, I haven't made disk images (ye, I know, danger zone :smile: ) since they would've been huge and I don't have a capacity to store them. The drives themselves are "in use" again and thus I won't be able to provide you with detailed reports. The only way to investigate this further would be to try to reproduce the issue(s).

**Comment by Lazza** [comment]
I really really hope that `cd Parition0` is a typo you introduced in this post, not a command you gave, otherwise you didn't change directory and you pruned the real metadata files.

In any case, it seems to me that RecuperaBit recovered the files correctly. Any kind of damage following deletions or additional commands does not seem to be relatable to its operation. It is not a RecuperaBit bug.
