### ISSUE TITLE
README is unclear on savefiles

### ISSUE THREAD

**Issue by Monkeyfume** [Lazza/RecuperaBit#42]
I've had to completely scan my drive three times today because I didn't specify an output directory at my initial issuance of the command to run the program! This has been an arduous process. The README suggests using parameter -s to load from a savefile but it's unclear on how to create a savefile after a scan in the first place. I'm very glad and thankful that you've put together this program, but I wish the README were more clear on this issue. How can savefiles be created?

**Comment by Lazza** [comment]
> I've had to completely scan my drive three times today because I didn't specify an output directory

Why? As written in the README, you do not have to as you can rely on the default output directory:

> These are exported in the directory specified by `-o` **(or `recuperabit_output`).**

Regarding your second point:

> it's unclear on how to create a savefile after a scan in the first place

You do not create the file, the programs creates one for you (but you have to provide a file name). The README says:

> The first time, after the scanning process, results are saved in the file. After the first run, the file is read to only analyze interesting sectors and speed up the loading phase.

---

Of course if you can suggest a better wording for the README file I would gladly review it and merge it.

**Comment by Monkeyfume** [comment]
>Why? As written in the README, you do not have to as you can rely on the default output directory ...

The default output directory was located on an SSD that was not large enough to hold the entire contents of the HDD I was copying from!

>You do not create the file, the programs creates one for you (but you have to provide a file name) ... Of course if you can suggest a better wording for the README file I would gladly review it and merge it.

Reading this part again, it makes more sense now. Just to confirm, if I wanted to recover the contents of /dev/sdc into the default output directory and create a savefile, could I use the following command?:

 `$ main.py -s savefile.txt /dev/sdc`

**Comment by Lazza** [comment]
> was located on an SSD that was not large enough

Ah sorry, I thought you were complaining about problems related to the creation of the directory. I get from your reply that the directory gets created correctly.

> could I use the following command?

Yes! You could also use it again after the initial scan is completed, to reload the same file. Currently the save file is only used to speed up the initial scanning phase. In the future, I hope to make it even more useful.
