### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by henri-eising** [Lazza/RecuperaBit#50]
Hi there, I'm trying to recover an external 4tb WD My Book drive. on which I accidentally used Startup Disk Creator to create an Ubuntu startup disk, so I think the first 3 or 4 gigs may be overwritten. so I tried recuperabit and it works fine until parsing the INDX records, then the program quits with next error:

```
INFO:root:Found NTFS file record at sector 3906986000
INFO:root:Found NTFS boot sector at sector 7813969912
INFO:root:First scan completed
INFO:root:Saving results to uitvoer.save
INFO:root:Parsing MFT entries
INFO:root:Parsing INDX records
Traceback (most recent call last):
  File "/usr/local/bin/recuperabit", line 385, in <module>
    main()
  File "/usr/local/bin/recuperabit", line 367, in main
    parts.update(scanner.get_partitions())
  File "/home/henri/RecuperaBit/recuperabit/fs/ntfs.py", line 733, in get_partitions
    parsed = parse_indx_record(dump)
  File "/home/henri/RecuperaBit/recuperabit/fs/ntfs.py", line 182, in parse_indx_record
    name_ok = file_name['name'] is not None
UnboundLocalError: local variable 'file_name' referenced before assignment
```

Please any advice on what might be wrong, and what to do.

I'm using Ubuntu 18.04 LTS
Python 2.7.15rc1 installed

greetings Henri

**Comment by Lazza** [comment]
Now it should be fixed. Please update and try again.
