### ISSUE TITLE
PDFs hosted on scribd require registration to download

### ISSUE THREAD

**Issue by dmhowcroft** [Lazza/RecuperaBit#52]
I'm interested in understanding how this works and reading your thesis, but Scribd only allows downloads when you register for an account.

Have you considered including it in this repo or posting it on arXiv or some other service that does not require registration?

**Comment by Lazza** [comment]
Ah, right. Please check out the archive of theses here:

http://dspace.unive.it/handle/10579/7912

You have to click on the document-shaped icon, or on "Mostra/apri" on the right.
