### ISSUE TITLE
crash on german umlauts can't encode character u'\xf6'

### ISSUE THREAD

**Issue by H4R0** [Lazza/RecuperaBit#55]
so im trying to recover a drive that got erased with hddscan, the erase option got instantly aborted only the first 1mb of the disk shows the hddscan overwrite pattern.

whenever i try to do a tree output or restore recuperabit crashes with the following message:
`UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 66: ordinal not in range(128)`

im using git master, the crash occurs after some seconds after it already restored about 300mb of files

traceback:
> INFO:root:Restoring #273517 Root/Program Files/Windows NT/TableTextService/TableTextService.dll
Traceback (most recent call last):
  File "/usr/lib/pypy/lib-python/2.7/logging/__init__.py", line 897, in emit
    stream.write(fs % msg.encode("UTF-8"))
  File "/usr/lib/pypy/lib-python/2.7/codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 62: ordinal not in range(128)
Logged from file logic.py, line 231
Traceback (most recent call last):
  File "main.py", line 385, in <module>
    main()
  File "main.py", line 382, in main
    interpret(cmd, arguments, parts, shorthands, args.outputdir)
  File "main.py", line 191, in interpret
    logic.recursive_restore(myfile, part, partition_dir)
  File "/recupera/recuperabit/logic.py", line 258, in recursive_restore
    recursive_restore(child, part, outputdir, make_dirs=False)
  File "/recupera/recuperabit/logic.py", line 258, in recursive_restore
    recursive_restore(child, part, outputdir, make_dirs=False)
  File "/recupera/recuperabit/logic.py", line 258, in recursive_restore
    recursive_restore(child, part, outputdir, make_dirs=False)
  File "/recupera/recuperabit/logic.py", line 232, in recursive_restore
    if not makedirs(restore_path):
  File "/recupera/recuperabit/logic.py", line 196, in makedirs
    os.makedirs(path)
  File "/usr/lib/pypy/lib-python/2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 66: ordinal not in range(128)

**Comment by H4R0** [comment]
anything i tried did not work, in the end the following pr fixed it
https://github.com/Lazza/RecuperaBit/pull/38

the restore is running now i will verify the result once its finished

**Comment by H4R0** [comment]
i get the same exception with the dfr-test image

my environment is a docker container with debian:latest
i only installed python, pypy and git

**Comment by Lazza** [comment]
Well, it's very unusual to run RecuperaBit in Docker. Given that it works on Linux, macOS, Windows and even Android without external dependencies, it might be way easier to just unpack it in a directory and run it from there.

I agree that there are some Unicode issues when the environment is not set correctly to UTF-8 (you might want to check how the locale is configured in the container) but this is really a mess on Python 2.

Hopefully, when there will be the time to do a Python 3 rewrite, the issues will be gone as a consequence.

**Comment by H4R0** [comment]
imho i dont think its that uncommom, its always good to run untrusted code inside a chroot, container or vm. The RecuperaBit codebase is very small so its easy to make an audit but this is often not the case for other projects especially with many dependencies to other packages.

I fixed the locale meanwhile, would it be ok for you if i publish and maintain a RecuperaBit docker container on hub.docker.com ?

**Comment by Lazza** [comment]
> this is often not the case for other projects

Well, OK, I can't speak for other projects, I was speaking for mine. 😛 I wonder if Docker introduces any performance penalty. Sometimes RecuperaBit is already slow when run natively... but I digress.

> would it be ok for you

### Yes 😄 

You don't need permission as the code is GPL'ed, but nevertheless I quite like the idea. Thank you for proposing it.
