### ISSUE TITLE
Feature Request: Restore atime, mtime, ctime

### ISSUE THREAD

**Issue by H4R0** [Lazza/RecuperaBit#58]
Restored files should contain file attibutes like last accessed, last modified, created at timestamps.

It should be possible to extract the values from the MFT and set them after the file write.

**Comment by mirh** [comment]
It should be possible indeed, or at least other programs don't seem to have problems recovering it. 
Why did you close this?

https://docs.python.org/library/os.html#os.utime

**Comment by H4R0** [comment]
There is no way to change the creation time under linux.

https://github.com/Lazza/RecuperaBit/issues/21

**Comment by mirh** [comment]
You can actually change c***r***time in linux, with some very specialized hacktool. 
The thing is, "creation time" for files in linux doesn't technically exist. 
Yes all its newest file systems do register something akin to this datum. But this is completely out of fancy, and it is a property belonging to the inodes AFAIK, not the actual files. 

And for this reason, I think, phyton only supports access and modify dates. 
But I don't see why those already couldn't be legitly supported (put even aside that if you are working in Windows, you have [no limitations](https://stackoverflow.com/questions/4996405/how-do-i-change-the-file-creation-date-of-a-windows-file))
