### ISSUE TITLE
rescuing ntfs compressed data - mft / drive "broken"

### ISSUE THREAD

**Issue by james-cook** [Lazza/RecuperaBit#67]
Situation:
I have an extenal usb hdd. Plugging it into Windows gives me a "unusable please format" kind of error message. i.e. chkdsk cannot be run - no drive letter.
It does look as if there is some damage physical/logical on the drive. (how it came to this I'm unsure - "could have been" an ntfs driver on mac or... (this happened some months ago...)
my memory is also that crash occured just after I renamed a directory at the top level...)

So, I tried (gnu) **ddrescue**-ing the drive. This ran for 6 or so months(!) and the error stats are something like: 
**1TB drive, rescued 980552MB, Errsize 7029MB, errors 5421** 
So, on the face of it, the majority of "data" is "OK". But there are errors...

I tried _testdisk_ on the image and copied out recognised data but this only finds a fraction of the data/directories at the top level of the disk - i.e. 3 or 4 directories at the top level (during the copy testdisk gave me 2 warnings:
> ntfs_mst_post_read_fixup_warn: magic: 0x00000000  size: 1024   usa_ofs: 0  usa_count: 65535: Invalid argument
> Record 3120700 has no FILE magic (0x0)).

"Repairing" the MFT from the mirror via the boot options in _testdisk_ did not reveal any new files.
In total testdisk rescued 59GB of data in 21000 files.

Then I ran __recuperabit__ using python64 2.7.6 on Windows8(!) on the image and this does a **great job :)** - finds a much greater structure of files, And the non-compressed files were rescued using `restore 586 5` - the 586 partition was the first partition in the _recuperabit_ list and seems to contain ALL the data I was looking for.

Now, of course, the majority of my files were in compressed directories to save space :(
In total _recuperabit_ rescued 142GB of data in 3 million files.

My questions are:

1. am I missing something with _testdisk_ that leads to such poor recovery in testdisk?
2. _recuperabit_ seems to build a new(?) $MFT file in the root directory - can this be used in any way to rescue the data - e.g. 
  `<someprogram(!)> <image file> <$MFT from _recuperabit_> <output directory>`
  were "someprogram" is something like some utility in e.g. nttools (ntfsprogs) that could be simply invoked...
3. I ran _recuperabit_ ON windows - does this give me any more chances to rescue the compressed data (native support/auto decompress)...
    e.g.: could any of the _recuperabit_ output files (savefile, csv file etc.) be used to scan the image again and extract the compressed files using some other program?

Obviously I'm not an expert - if I comment out the "exit" in your code (after the test for compressed data) would the non-resident compressed file be actually output? And could anything be "done" with this file/directory (like setting the compressed attribute etc.) to rescue/decompress this data?

Do you have any recommendations/ideas for me? - the data does seem tantalisingly close to being rescued

**Comment by Lazza** [comment]
> So, on the face of it, the majority of "data" is "OK". But there are errors...

Yes, you still have 7 GB of errors, I am afraid.

> Now, of course, the majority of my files were in compressed directories to save space :(

Ouch, unfortunately NTFS compression is not currently supported (and I was not able to find much information about how it is supposed to work). Sparse files do work, though.

1. As far as I know, Testdisk simply reads the directory tree from the top so you just need a few damaged nodes to drop huge parts of the tree
2. It builds a tree in some form (not a MFT file) but it resides in memory... it would be easier to implement NTFS compression in RecuperaBit if I manage to understand how it works
3.  I don't think so: RecuperaBit is entirely self-contained and uses **zero external libraries** (other than standard Python packages)

> would the non-resident compressed file be actually output?

Yes, but it's not readable, I think.

> And could anything be "done" with this file/directory (like setting the compressed attribute etc.) to rescue/decompress this data?

I assume that if you manually copy the files inside a NTFS drive and then hack the file system to set the compressed flag, it could work. That sounds like an extremely hacky way to do the job and it could destroy the file system in which you are tinkering with the flags.

> Do you have any recommendations/ideas for me?

This might not seem like a great reccomendation, I am afraid you cannot do a lot with RecuperaBit if you have compressed files. You might want to try *Restorer Ultimate Pro* but it is a commercial tool.

**Comment by james-cook** [comment]
Hallo Lazza, 
thanks very much for your thoughts on this :) and all the work inside _recuperabit_!

It looks like any solution (if at all possible) would take "some time" to investigate.
I've seen the issue at https://github.com/Lazza/RecuperaBit/issues/44 and may be able to contribute if
I can find the time.
