### ISSUE TITLE
Can RecuperaBit recover partitions whole?

### ISSUE THREAD

**Issue by Kaos-Industries** [Lazza/RecuperaBit#70]
Apologies if this has been asked for, but I'm confused as to whether RecuperaBit is just a file recovery program, or whether it can also restore partitions whole to make the old folder structure browsable again, like TestDisk claims to be able to do. Thanks.

**Comment by Lazza** [comment]
RecuperaBit operates strictly read only and it does not write anything on the source drive.

Thus you will need to extract the files in a different directory if you want to browse them.

**Comment by Kaos-Industries** [comment]
> 
> 
> RecuperaBit operates strictly read only and it does not write anything on the source drive.
> 
> Thus you will need to extract the files in a different directory if you want to browse them.

? I'm not seeing how that's a response to my question exactly. Are you saying that it only does file recovery, like PhotoRec?

**Comment by Lazza** [comment]
You asked whether it can recover partitions by writing them in place like Testdisk does, which clearly requires to modify the source data.

If A implies B, not B implies not A. 😅 

To explore the recovered directories and files you first need to recover them to a different output directory.

I don't understand why you are comparing RecuperaBit to Photorec. The latter is a file carver that only recovers file contents of specific types (no directories, no file names) while RecuperaBit restores the data based on incomplete file system metadata as is documented.

The two programs work in totally opposite ways.
