### ISSUE TITLE
Help needed with running on windows

### ISSUE THREAD

**Issue by rabea98** [Lazza/RecuperaBit#74]
How to use the tool with a connected partition in windows?

**Comment by Lazza** [comment]
You should run RecuperaBit on a disk image, not on a real partition. Especially on Windows where the raw devices are not easily exposed as files.

**Comment by rabea98** [comment]
> You should run RecuperaBit on a disk image, not on a real partition. Especially on Windows where the raw devices are not easily exposed as files.

What tool would you recommend to create an image file?

**Comment by Lazza** [comment]
You can use FTK Imager or really your favorite tool of choice for this job.

**Comment by mirh** [comment]
It's not really hard to access real "physical" drives (as long as your command prompt is run as admin). 
https://groups.google.com/g/comp.lang.python/c/vPyuOwRVC6c/m/2GrcFrnjsmUJ
https://stackoverflow.com/questions/6522644/how-to-open-disks-in-windows-and-read-data-at-low-level/#6523306

Except if you are using pypy3, for some reason. I couldn't get it to work in any way.
