### ISSUE TITLE
Restoring lost partition on external NTFS hard drive

### ISSUE THREAD

**Issue by stephaniewj** [Lazza/RecuperaBit#76]
Hello Lazza,
I am not sure if you can help and I am sorry if this is not the place to put this,, but I downloaded a windows update to my external HDD to update a computer later, because it said the device had to be at least 8GB. This turned my 1TB drive into a 32GB partition with the windows OS files on it (only 4GB is over written) with the original 899.51 GB partition as unallocated.

How can I use RecuperaBit to recover the unallocated partition and get my files and folder structures back? Is this something RecuperaBit can do?

I have no programming knowledge but I read about RecuperaBit and I would be very grateful if you can help.

**Comment by Lazza** [comment]
You cannot use this program to "undelete" the partition and get it back on the current drive, but you might be able to recover a copy of its contents to a different drive. This holds if the partition was NTFS-formatted and the files were not using NTFS compression (this one is not currently supported).

**Comment by stephaniewj** [comment]
Hello,
Thank you so much for replying!Unfortunately I have no idea what NTFS compression means, I don't know if the files were using NTFS compression or not, but I believe the external hard drive used to be an NTSF, because I thought all hard drives are supposed to be NTSF.
Also, is it possible for you to explain in detail how I can try copying the contents to a new hard drive? I don't quite understand the instructions or indeed, how to use 'Git'. If the copying works, will the files be corrupted, or lose their date information and be named like File1, or will it copy them as it was, with the folder structure and everything? Just so I can be mentally prepared.
Appreciate your reply during what is supposed to be a holiday season, gives me some hope at life at least.Stephanie
    On Thursday, 31 December 2020, 05:32:19 am AEDT, Andrea Lazzarotto <notifications@github.com> wrote:  
 
 


You cannot use this program to "undelete" the partition and get it back on the current drive, but you might be able to recover a copy of its contents to a different drive. This holds if the partition was NTFS-formatted and the files were not using NTFS compression (this one is not currently supported).

**Comment by Lazza** [comment]
> I don't quite understand the instructions or indeed, how to use 'Git'

Please note that RecuperaBit is aimed to Digital Forensics professionals and requires command line usage. If you don't fall into this category of people, you might find it quite hard to use (also, the textual interface itself needs a revamp but I didn't have the time yet).

In case you are just trying to perform a "user-friendly" recovery task you might be better off using some commercial data recovery program. For instance, I had several successfull experiences with [Restorer Ultimate (Pro)](https://www.bitmart.net/restorer-ultimate/) in the past. As far as I know it also supports NTFS compressed files so you don't have to worry about that.

Good luck!

**Comment by stephaniewj** [comment]
Thank you Andrea for the information, but I have tried some software already. Data recovery is incredibly disheartening so I am looking for a way to recover the actual partition itself. From what I gathered, I RecuperaBit does that (when you said it might be possible to copy the contents to a different drive). Maybe I misunderstood. Can you confirm what you meant by that? If it was successful, does copying the drive result in folder structure and names etc? Would it be an exact copy?
Thank you.

**Comment by Lazza** [comment]
As written in the README (see also my "PS" above), RecuperaBit reads the file system structure from the MFT.

> Would it be an exact copy?

This is impossible to answer without knowing the exact condition of the drive. Only you can verify it.
