### ISSUE TITLE
1.1.5-dev TypeError: 'bytes' object does not support item assignment

### ISSUE THREAD

**Issue by sauron3256** [Lazza/RecuperaBit#82]
After making the nescessary changes from the diff in #80 and running the scan again using the same drive, I got the following error:

> INFO:root:Parsing MFT entries
> Traceback (most recent call last):
> File "/home/lef/RecuperaBit-1.1.4/main.py", line 374, in
> main()
> File "/home/lef/RecuperaBit-1.1.4/main.py", line 357, in main
> parts.update(scanner.get_partitions())
> File "/home/lef/RecuperaBit-1.1.4/recuperabit/fs/ntfs.py", line 695, in get_partitions
> parsed = parse_file_record(dump)
> File "/home/lef/RecuperaBit-1.1.4/recuperabit/fs/ntfs.py", line 149, in parse_file_record
> _apply_fixup_values(header, entry)
> File "/home/lef/RecuperaBit-1.1.4/recuperabit/fs/ntfs.py", line 102, in _apply_fixup_values
> entry[pos-2:pos] = entry[offset + 2i:offset + 2(i+1)]
> TypeError: 'bytes' object does not support item assignment

**Comment by Lazza** [comment]
Alright, my bad. Please kindly test with the latest code.

**Comment by sauron3256** [comment]
Thank you. Running the scan again. I'll update if I encounter any errors.

**Comment by Lazza** [comment]
Thank you. Please also let me know if you end the procedure successfully so I can publish a new release. 🙂
