### ISSUE TITLE
What'll happen if there's not enough space during restore?

### ISSUE THREAD

**Issue by ilos-vigil** [Lazza/RecuperaBit#89]
First of all, thank you for creating this software and make it FOSS.

Here's my situation. I have about 2TB data on damaged HDD, but the partition of the `-o OUTPUTDIR` size is only about 1TB. My question are,
1. What'll happen when the partition ran out of space during restoration process?
2. If the software will crash or stuck, should i move file which already recovered (before the partition ran out of space) to another directory (i have another HDD & flash drive with smaller size) ?

Edit: In the end, i moved file which already recovered.

**Comment by Lazza** [comment]
If you fill up the drive I don't think it's going to end up pretty well. You are probably going to encounter an I/O error and see the program crash.

You might want to recover some directories instead of the whole tree at once.

**Comment by ilos-vigil** [comment]
Thanks for answering, i'll do that next time.
