### ISSUE TITLE
Recuperabit

### ISSUE THREAD

**Issue by zicolotto** [Lazza/RecuperaBit#97]
Salve,
vi ho scritto anche una email zicozichetto, volevo sapere se recuperabit, funziona anche su Fat32? L'ho provato su Windows per dei file persi su una pen drive da 8 gb formattata e poi sovrascritra per sbaglio tramite l'utility Rufus, ma non so se è corretto creare l'immagine dell'unità esterna USB della pen drive per poi darla in pasto a recuperabit, il tool parte, ma il risultato è che mi trova solo cose inutili, con file che iniziano con la lettera $ , forse non si può usare su un supporto esterno di tipi fat32? I file più importanti che mi servivano maggiormente,  si trovavano nella directory root della pen drive. Ringrazio per eventuali delucidazioni

**Comment by gioxx** [comment]
Prima riga del file [README](https://github.com/Lazza/RecuperaBit/blob/master/README.md) del progetto:

> A software which attempts to reconstruct file system structures and recover files. **Currently it supports only NTFS.**

**Comment by Lazza** [comment]
> non so se è corretto creare l'immagine dell'unità esterna USB della pen drive per poi darla in pasto a recuperabit

Sì, è assolutamente opportuno lavorare sulle immagini disco.

> volevo sapere se recuperabit, funziona anche su Fat32?

No, RecuperaBit è un software dedicato alla ricostruzione forense di partizioni NTFS. Non supporta FAT32.

**Comment by zicolotto** [comment]
Thanks for the reply, I wanted to ask you if you know a way to recover data
from USB media having Fat32 filesystem after formatting and rewriting, is
it possible to recover the state before formatting?
Thanks
Zico

Il giorno sab 13 nov 2021 alle ore 23:05 Andrea Lazzarotto <
***@***.***> ha scritto:

**Comment by Lazza** [comment]
I suppose your best bet is to use other tools that work with FAT32, such as Testdisk or Photorec (open source) or Restorer Ultimate Pro (proprietary).
