### ISSUE TITLE
Error does not work, not sure if the script is incomplete, or if I used it wrong or both or neither.

### ISSUE THREAD

**Issue by left1000** [Lazza/RecuperaBit#98]
python 3.10
command:

    py main.py -s "C:\RecuperaBit-1.1.5\savefile1" -o "C:\RecuperaBit-1.1.5\recovered" K:\imagefileg1

output:

```
INFO:root:First scan completed
INFO:root:Saving results to C:\RecuperaBit-1.1.5\savefile1
INFO:root:Parsing MFT entries
then
error:

  File "C:\RecuperaBit-1.1.5\main.py", line 374, in <module>
    main()
  File "C:\RecuperaBit-1.1.5\main.py", line 357, in main
    parts.update(scanner.get_partitions())
  File "C:\RecuperaBit-1.1.5\recuperabit\fs\ntfs.py", line 695, in get_partitions
    parsed = parse_file_record(dump)
  File "C:\RecuperaBit-1.1.5\recuperabit\fs\ntfs.py", line 151, in parse_file_record
    attributes = _attributes_reader(entry, header['off_first'])
  File "C:\RecuperaBit-1.1.5\recuperabit\fs\ntfs.py", line 110, in _attributes_reader
    attr, name = parse_mft_attr(entry[offset:])
  File "C:\RecuperaBit-1.1.5\recuperabit\fs\ntfs.py", line 91, in parse_mft_attr
    data = unpack(content[:size], attr_types_fmt[name])
  File "C:\RecuperaBit-1.1.5\recuperabit\utils.py", line 89, in unpack
    result[label] = formatter(data[low:high+1])
  File "C:\RecuperaBit-1.1.5\recuperabit\fs\ntfs_fmt.py", line 81, in index_root_parser
    entries = index_entries(dump[offset:])
  File "C:\RecuperaBit-1.1.5\recuperabit\fs\ntfs_fmt.py", line 58, in index_entries
    parsed = unpack(dump[offset:], indx_dir_entry_fmt)
  File "C:\RecuperaBit-1.1.5\recuperabit\utils.py", line 89, in unpack
    result[label] = formatter(data[low:high+1])
  File "C:\RecuperaBit-1.1.5\recuperabit\fs\ntfs_fmt.py", line 127, in try_filename
    unpack(dump, attr_types_fmt['$FILE_NAME'])
  File "C:\RecuperaBit-1.1.5\recuperabit\utils.py", line 89, in unpack
    result[label] = formatter(data[low:high+1])
  File "C:\RecuperaBit-1.1.5\recuperabit\fs\ntfs_fmt.py", line 47, in windows_time
    converted = datetime.utcfromtimestamp(value/10.**7 - 11644473600)
OSError: [Errno 22] Invalid argument
```

Of course this could be because this is meant for python 3.9 or it could be because I'm meant to edit the script if various locations that are indicated in comments that I only 50% comprehend. Felt like I should write this feedback though.

**Comment by Lazza** [comment]
This is super weird. It should be already handled:

https://github.com/Lazza/RecuperaBit/blob/728e978e459463e259bacca18d8a13a66241f309/recuperabit/fs/ntfs_fmt.py#L49

Can you try to "destroy" the `windows_time` function and let it always return 0?

You will lose the timestamps, but at least we can see if the other parts are working.

**Comment by Lazza** [comment]
Actually, maybe the issue is due to the way I wrote line 49. Can you try with this one instead?

    except (ValueError, OverflowError, OSError), as e:

**Comment by left1000** [comment]
Anyway to resume my progress? Load the saved file from my last run? otherwise it'll take me another day to test this one change :)

**Comment by left1000** [comment]
> Actually, maybe the issue is due to the way I wrote line 49. Can you try with this one instead?
> 
> ```
> except (ValueError, OverflowError, OSError) as e:
> ```


Now I run the script and see this instantly:

     ___                                ___ _ _
    | _ \___ __ _  _ _ __  ___ _ _ __ _| _ |_) |_
    |   / -_) _| || | '_ \/ -_) '_/ _` | _ \ |  _|
    |_|_\___\__|\_,_| .__/\___|_| \__,_|___/_|\__|
                    |_|   v1.1.5
    (c) 2014-2021, Andrea Lazzarotto <andrea.lazzarotto@gmail.com>
    Released under the GPLv3

ERROR:root:Unable to open image file!


I'm not sure if I screwed up editing line 49, or what


I will note though that your prior comment is a bit odd.

Line 49 is:"     except ValueError:"
I'm using the release version, I'm betting you're referring to a version other than the release version.

So, I should switch to the version you're using, and then  
"       except (ValueError, OverflowError, OSError): "
may very well be correct, it was not my line 49.

**Comment by left1000** [comment]
Okay so I downloaded the project from git as a clone instead of taking the old release from February and I get 

ERROR:root:Unable to open image file!

with your old line 49 
 except (ValueError, OverflowError, OSError): 

then I tried to destroy windows time function to return 0 and same issue

then I tried xcept (ValueError, OverflowError, OSError) as e:

same result... it's strange, it's almost like the file isn't accessible anymore, and this new message has nothing to do with the code change, but well, any test I use to determine if the file is accessible shows that it is accessible....

wait, actually, going back to the original code, gives the same error...

so nothing I've written in this post or the previous post is relevant at all :-p

**Comment by Lazza** [comment]
> You should consider putting out a new release I guess

I was waiting to see if there were some other issues, but given that this problem seems to be impacting a few users I will now publish a new release on GitHub. Thank you for the suggestion and for testing the latest commits.
